package app.gamenative.ui.enums

enum class AppOptionMenuType(val text: String) {
    StorePage("Open store page"),
    CreateShortcut("Create shortcut"),
    ExportFrontend("Export for frontend"),
    RunContainer("Open container"),
    EditContainer("Settings"),
    ResetToDefaults("Reset container"),
    Container("Container"),
    GetSupport("Get support"),
    ResetDrm("Reset DRM"),
    UseKnownConfig("Use known config"),
    ImportConfig("Import config"),
    ExportConfig("Export config"),
    Uninstall("Uninstall"),
    VerifyFiles("Verify files"),
    Update("Update"),
    MoveToExternalStorage("Move to external storage"),
    MoveToInternalStorage("Move to internal storage"),
    ForceCloudSync("Force cloud sync"),
    ForceDownloadRemote("Force download remote saves"),
    ForceUploadLocal("Force upload local saves"),
    CustomImage("Custom image"),
    ImportSave("Import Save"),
    ExportSave("Export Save"),
    TestGraphics("Test graphics"),
    ManageGameContent("Manage DLC"),
    Controller("Controller"),
    Saves("Saves");
}
